### ISSUE TITLE
Hey test user here

### ISSUE THREAD

**Issue by hrittikhere** [aksagarwal42/aksagarwal42#1]
Hi @aksagarwal42,
I hope you're doing well.
I am testing something over here can you reply anything here? Like send me a HI and then maybe wait for my reply 🗡️ 
Thanks :D

**Comment by aksagarwal42** [comment]
Hi @hrittikhere,
Works like a charm!
😃

**Comment by hrittikhere** [comment]
Sending a text from mail!

**Comment by hrittikhere** [comment]
Thank you for your service :)
